In [1]:
import numpy as np

In [3]:
a = [20,30,40]

In [5]:
type(a)

list

In [7]:
np.array(a)

array([20, 30, 40])

In [11]:
matrix = [[10,20,30],[20,30,40],[30,40,50]]

In [13]:
matrix[1][0]

20

In [15]:
np.array(matrix)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.random.randn(3)

array([ 0.82204043,  0.45685092, -0.35605179])

In [44]:
np.random.randint(3)

2